version: '3.9'

services:
  server:
    container_name: admin-server
    image: '$CI_IMAGE_NAME'
    env_file: .env
    depends_on:
      - db
    ports:
      - "9001:9001"
  admin-db:
    image: postgres:16-alpine
    restart: always
    ports:
      - '2345:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nest-prisma
    volumes: 
     - ./database/postgres:/var/lib/postgresql/data